# Generated by Django 4.2.5 on 2023-09-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('hobby', models.CharField(max_length=40, null=True)),
                ('year', models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third'), ('4th', 'Fourth')], max_length=4)),
                ('is_cr', models.BooleanField(default=False)),
                ('registration_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
