# Generated by Django 4.2.5 on 2023-09-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_cr',
            field=models.BooleanField(default=False, verbose_name='class representatice'),
        ),
    ]
