# Generated by Django 4.2.5 on 2023-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_is_cr'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_cr',
            field=models.BooleanField(default=False, verbose_name='class representative'),
        ),
    ]
